### ISSUE TITLE
Add global error message system

### ISSUE THREAD

**Issue by robshape** [robshape/frija#2]
## Description
_What is the problem? Provide screenshots when suitable. Do you know how it can be solved?_

Unified way of showing error messages to the user. It should be invokable from all parts of the application. It could use the existing Apollo GraphQL local state implementation. (Or you could introduce Redux to the application.)

## Tasks
_Break the solution down to tasks if possible._

- [ ] Add local state for error messages.
- [ ] Add functionality for adding error message to the local state. (For example, `showError('Error message);`.)
- [ ] Create React component for showing error message to the user.
- [ ] Connect React component to local state for error messages.
- [ ] Add error handling to authentication user flow. Show error messages to the user.

**Comment by robshape** [comment]
https://reactjs.org/docs/error-boundaries.html
